import type { Metadata } from "next";
import "./../styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Clock from "@/components/Clock";
import ClientProvider from "@/components/ClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="main-page">
        <ClientProvider>
          <div className="layout-container">
            <Header />
            <Clock />
            <main className="content-container">{children}</main>
            <Footer />
          </div>
        </ClientProvider>
      </body>
    </html>
  );
}
